"""empty message

Revision ID: 91767fb0cd51
Revises: 
Create Date: 2023-08-05 09:53:34.632928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91767fb0cd51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=128), nullable=True),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_log_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_url_log_timestamp_utc'), ['timestamp_utc'], unique=False)

    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longUrl', sa.String(length=128), nullable=True),
    sa.Column('shortUrl', sa.String(length=16), nullable=True),
    sa.Column('isEvil', sa.Boolean(), nullable=True),
    sa.Column('timestamp_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urls_longUrl'), ['longUrl'], unique=True)
        batch_op.create_index(batch_op.f('ix_urls_shortUrl'), ['shortUrl'], unique=True)
        batch_op.create_index(batch_op.f('ix_urls_timestamp_utc'), ['timestamp_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urls_timestamp_utc'))
        batch_op.drop_index(batch_op.f('ix_urls_shortUrl'))
        batch_op.drop_index(batch_op.f('ix_urls_longUrl'))

    op.drop_table('urls')
    with op.batch_alter_table('url_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_log_timestamp_utc'))
        batch_op.drop_index(batch_op.f('ix_url_log_ip'))

    op.drop_table('url_log')
    # ### end Alembic commands ###
